name: CI
on:
  push:
    branches:
      - rust-rewrite

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build binary
        run: cargo test
  publish:
    name: Publish to Docker
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create and publish to Docker Hub
      uses: hannes-hochreiner/github-actions/publish-on-docker-hub@v1.3.3
      with:
        docker-user-name: ${{ secrets.DOCKER_USER }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}
