name: CI
on:
  push:
    branches:
      - rust-rewrite


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install cross
        run: cargo install cross
      - name: Test project
        run: cross test --target arm-unknown-linux-musleabihf
      - name: Build project
        run: cross build --target arm-unknown-linux-musleabihf --release --locked
